import { Router } from "express";
import { authMiddleware } from "../middleware/auth";
import { createPatient, getPatients, getPatient, updatePatient, deletePatient } from "../controllers/patient.controller";
const router = Router();
router.post("/", authMiddleware(["doctor","Paciente"]), createPatient);
router.get("/", authMiddleware(["doctor","Paciente"]), getPatients);
router.get("/:id", authMiddleware(["doctor","Paciente"]), getPatient);
router.put("/:id", authMiddleware(["doctor","Paciente"]), updatePatient);
router.delete("/:id", authMiddleware(["doctor","Paciente"]), deletePatient);
export default router;
